# Generated by Django 3.2.2 on 2021-05-29 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('keyword', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=50)),
                ('address', models.TextField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('fax', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('smtpserver', models.CharField(max_length=50)),
                ('smtpemail', models.CharField(max_length=50)),
                ('smtppassword', models.CharField(max_length=50)),
                ('smtpport', models.CharField(max_length=50)),
                ('icon', models.ImageField(blank=True, max_length=5, upload_to='')),
                ('facebook', models.CharField(max_length=50)),
                ('instagram', models.CharField(max_length=50)),
                ('twitter', models.CharField(max_length=50)),
                ('abouts', models.TextField(max_length=50)),
                ('contact', models.CharField(max_length=50)),
                ('references', models.TextField(max_length=50)),
                ('status', models.CharField(choices=[('True', 'Evet'), ('False', 'Hayır')], max_length=10)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
