# Generated by Django 3.2.2 on 2021-05-29 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210529_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='icon',
            field=models.ImageField(blank=True, max_length=50, upload_to=''),
        ),
    ]
