# Generated by Django 3.2.2 on 2021-05-16 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yurtdışı', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Yurtiçi',
            new_name='Yurtdışı',
        ),
    ]
