# Generated by Django 3.2.2 on 2021-05-22 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yurtiçi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Şehirler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('keyword', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('status', models.CharField(choices=[('True', 'Evet'), ('False', 'Hayır')], max_length=10)),
                ('şehir', models.TextField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Category',
            new_name='Bölge',
        ),
        migrations.DeleteModel(
            name='Yurtiçi',
        ),
        migrations.AddField(
            model_name='şehirler',
            name='bölge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yurtiçi.bölge'),
        ),
    ]
