# Generated by Django 3.2.2 on 2021-06-26 10:38

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yurtiçi', '0003_auto_20210529_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='şehirler',
            name='şehir',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
