# Generated by Django 3.2.2 on 2021-07-01 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yurtiçi', '0004_alter_şehirler_şehir'),
    ]

    operations = [
        migrations.RenameField(
            model_name='şehirler',
            old_name='şehir',
            new_name='detay',
        ),
    ]
