# Generated by Django 3.2.2 on 2021-07-01 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yurtiçi', '0007_alter_images_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bölge',
            name='image',
        ),
    ]
